version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: bibliodb
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: motdepasse
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U utilisateur" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bibliodb
      SPRING_DATASOURCE_USERNAME: utilisateur
      SPRING_DATASOURCE_PASSWORD: motdepasse
    ports:
      - "8080:8080"

volumes:
  db-data:
